# Generated by Django 3.1 on 2020-11-07 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 4, 17, 255326), editable=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 4, 17, 255326), editable=False),
        ),
    ]
