# Generated by Django 3.1 on 2020-11-07 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201107_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='modified',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 15, 5, 30, 775903), editable=False),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
