# Generated by Django 3.1 on 2020-11-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201112_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 20, 13, 59, 603056), editable=False),
        ),
    ]
